version: '3'

services:
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    # command: -config.file=/etc/loki/loki-config.yaml
    # volumes:
    #   # Loki configuration
    #   - ./loki-config.yaml:/etc/loki/loki-config.yaml
    networks:
      - loki-net

  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./promtail-config.yaml:/etc/promtail/promtail-config.yaml
    networks:
      - loki-net
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:latest
    # ports:
    #   - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - loki-net
    depends_on:
      - loki

  nginx:
    image: nginx:1.27.0
    ports:
      - "8888:80"
    volumes:
       - ./conf.d:/etc/nginx/conf.d:ro
    networks:
      - loki-net


networks:
  loki-net:
    external: true